name: Deploy to Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'public/**'
      - 'vue.config.js'
      - '.github/workflows/pages-deploy.yml'

jobs:
  build-and-deploy:
    if: "!contains(toJSON(github.event.commits.*.message), '--skip-ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          persist-credentials: false
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn run build
        env:
          VUE_APP_SHA: ${{ github.sha }}
          VUE_APP_HTTPS: ${{ secrets.HTTPS }}
          VUE_APP_GTAG: ${{ secrets.GTAG }}
          VUE_APP_CDN: ${{ secrets.CDN }}
          USE_CDN: ${{ secrets.USE_CDN }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          git-config-name: アーミヤ
          git-config-email: amiya-bot@users.noreply.github.com
          branch: gh-pages
          folder: dist
          single-commit: true
